name: closet
description: A closet flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  bloc: ^8.0.3
  chewie: ^1.3.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  get_it: ^7.2.0
  intl: ^0.17.0
  map_launcher: ^2.2.2
  open_file: ^3.2.1
  path_provider: ^2.0.9
  provider: ^6.0.2
  qr_flutter: ^4.0.0
  sqflite: ^2.0.2
  video_player: ^2.2.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/gosuslugi.png
    - assets/icons/account.svg
    - assets/icons/order.svg
    - assets/icons/chat.svg
    - assets/icons/location.svg
    - assets/icons/phone.svg
    - assets/icons/login.svg
    - assets/icons/password.svg
    - assets/icons/email.svg
    - assets/icons/edit.svg
    - assets/icons/box.svg
    - assets/icons/support_chat.svg
    - assets/icons/new_order.svg
    - assets/icons/cctv.svg
    - assets/icons/open-lock.svg
    - assets/icons/stock.svg
    - assets/icons/completed.svg
    - assets/icons/not.svg
    - assets/video/video_surveillance.mp4

flutter_intl:
  enabled: true
