name: closet
description: A closet flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  get_it: ^7.2.0
  intl: ^0.17.0
  map_launcher: ^2.2.2
  path_provider: ^2.0.9
  provider: ^6.0.2
  sqflite: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/gosuslugi.png
    - assets/icons/account.svg
    - assets/icons/order.svg
    - assets/icons/chat.svg
    - assets/icons/location.svg
    - assets/icons/phone.svg
    - assets/icons/login.svg
    - assets/icons/password.svg
    - assets/icons/email.svg
    - assets/icons/edit.svg
    - assets/icons/box.svg
    - assets/icons/support_chat.svg
    - assets/icons/new_order.svg

flutter_intl:
  enabled: true
